---
Roles:
  # Ping role message
  Ping: "ping_IBNHRCEG7UOQR9JAVN2JS0UQ1GM45AEKBCK3HN2PXMO7F9UHKKG26UBLRJVAGJQLCZQPZ7HDI6X74F74OK9489YW4NRSJ5VTHDF3S9ENT1305M3J3A78GXO8NSG"
  # Pong role message
  Pong: "pong_IMJ9S1KJD8FZYCKF8ILPXES1RTR685OTYOJYKK5EDMU1AO2XVX8Z2X8VKXKJ1RS2EC06N8A01IM5AKB5PB135Q81NXXVN6QNGLRTCX6I5P566ZS9I7BGB0L3BMG"
Host: "localhost"
Ports:
  # Socket port
  Socket: "9988"